[DEFAULT]
backend = systemd
banaction = nftables
bantime = 1h
findtime = 10m
maxretry = 4
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w
bantime.rndtime = 10m

[sshd]
enabled = true
port = ssh
mode = aggressive
maxretry = 4

[recidive]
enabled = true
backend = auto
logpath = /var/log/fail2ban.log
banaction = nftables-allports
findtime = 1d
bantime = 1w
maxretry = 5
