server_tokens off;

map "$request_method:$uri" $gdns_wp_login_key {
    default "";
    "POST:/wp-login.php" $binary_remote_addr;
}

map "$request_method:$uri" $gdns_wp_xmlrpc_key {
    default "";
    "POST:/xmlrpc.php" $binary_remote_addr;
}

limit_req_zone $gdns_wp_login_key zone=gdns_wp_login:10m rate=6r/m;
limit_req_zone $gdns_wp_xmlrpc_key zone=gdns_wp_xmlrpc:10m rate=60r/m;
limit_req_status 429;
limit_req_log_level notice;
limit_req zone=gdns_wp_login burst=10 nodelay;
limit_req zone=gdns_wp_xmlrpc burst=30 nodelay;
